### ISSUE TITLE
[Blender] RNA_Types has no attribute 'Light'

### ISSUE THREAD

**Issue by HieuNguyenVu** [BabylonJS/Exporters#523]
Traceback (most recent call last):
  File "C:\Users\hieu\Downloads\blender-2.79a-windows64\2.79\scripts\modules\addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "C:\Users\hieu\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\babylon_js\__init__.py", line 86, in <module>
    from . import light_shadow
  File "C:\Users\hieu\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\babylon_js\light_shadow.py", line 168, in <module>
    default = False
AttributeError: 'RNA_Types' object has no attribute 'Light'

**Comment by deltakosh** [comment]
Pinging @Palmer-JC

**Comment by Palmer-JC** [comment]
The last exporter to run on Blender 2.7x is 5.4.
